### ISSUE TITLE
No PSFilterPdn.dll or PSFilterShim.exe files

### ISSUE THREAD

**Issue by andrewp85** [0xC0000054/PSFilterPdn#3]
There does not appear to be any files called PSFilterPdn.dll or PSFilterShim.exe in order to copy into the Effects folder in Paint.Net

**Comment by 0xC0000054** [comment]
> There does not appear to be any files called PSFilterPdn.dll or PSFilterShim.exe in order to copy into the Effects folder in Paint.Net

It sounds like you may have downloaded the source code instead of  PSFilterPdn.zip.
